set_property PACKAGE_PIN Y18 [get_ports {ws281x_data[0]}]
set_property PACKAGE_PIN Y19 [get_ports {ws281x_data[1]}]
set_property PACKAGE_PIN Y16 [get_ports {ws281x_data[2]}]
set_property PACKAGE_PIN Y17 [get_ports {ws281x_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ws281x_data[*]}]
set_property DRIVE 8 [get_ports {ws281x_data[*]}]
set_property SLEW SLOW [get_ports {ws281x_data[*]}]
